### ISSUE TITLE
Invalid Cast Exception occurs when script is compiled using Experimental Flag (Roslyn)

### ISSUE THREAD

**Issue by asalvo** [Redth/Cake.Android.Adb#3]
I am getting a Invalid Cast exception when I execute my build script simply by adding the #addin reference to Cake.Android.Adb. This happens on both OSX and Windows, but I was able to get a better stack trace on windows with the Cake verbosity level set to debug. 

Based on the stack trace, I am assuming this is due to using the Cake -experimental flag, which uses Roslyn to do the script compiling. 

Compiling build script...
C:\_files\projects\TrGit\DevOpsScripts\Cake\tools\Cake\Cake.exe : Error: System.InvalidCastException: Invalid cast from 'System.Int32' to 'Cake.AndroidAdb.PackageListState'.
At line:1 char:1
+ C:\_files\projects\TrGit\DevOpsScripts\Cake\tools\Cake\Cake.exe "Cake ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: System.I...kageListState'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Microsoft.CodeAnalysis.Scripting.Emit.ReflectionE
mitter.DefineParameter(MethodBuilder methodBuilder, ConstructorBuilder constructorBuilder, IParameterDefinition paramDef)
   at Microsoft.CodeAnalysis.Scripting.Emit.ReflectionEmitter.DefineParameters(MethodBuilder methodBuilder, ConstructorBuilder constructorBuilder, IMethodDefinition methodDef)
   at Microsoft.CodeAnalysis.Scripting.Emit.ReflectionEmitter.EmitWorker(IMethodReference entryPoint, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Emit.CommonCompilationExtensions.Emit(Compilation compilation, ModuleBuilder moduleBuilder, AssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, Boolean recoverOnError, DiagnosticBag diagnostics, CancellationToken cancellationToken, MethodInfo& entryPoint, Byte[]& compiledAssemblyImage)
   at Microsoft.CodeAnalysis.Scripting.ScriptBuilder.Build(Script script, DiagnosticBag diagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
   at Cake.Scripting.Roslyn.Nightly.DefaultRoslynNightlyScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

**Comment by Redth** [comment]
Guessing this is resolved in later versions of cake....
